import { sql } from "./client.ts";

export type BotUser = {
  id: string;
  name: string | null;
  telegramUserId: bigint | null;
  telegramUsername: string | null;
  telegramFirstName: string | null;
};

/**
 * Find-or-create a User row keyed by Telegram user id. Bot-only users have
 * `email` left NULL (the schema's `email @unique` index is partial — NULLs
 * are allowed and never collide). On every call we refresh display fields
 * so renamed Telegram accounts surface in announcements without a manual
 * resync.
 */
export async function findOrCreateTelegramUser(
  telegramUserId: number,
  attrs: { username?: string; firstName?: string },
): Promise<BotUser> {
  // Pass as string + explicit ::bigint cast: postgresjs's TS types for
  // bigint parameters are flaky and modern Telegram ids can exceed
  // Number.MAX_SAFE_INTEGER. String + cast sidesteps both problems.
  const tid = String(telegramUserId);
  const username = attrs.username ?? null;
  const firstName = attrs.firstName ?? null;

  // cuid()-shaped ids are generated by the Next app; for bot-only users we
  // use a `tg_<id>_<rand>` prefix to make their origin obvious in pgcli.
  const idHint = `tg_${telegramUserId}_${
    crypto.randomUUID().replace(/-/g, "").slice(0, 12)
  }`;

  const rows = await sql<BotUser[]>`
    WITH ins AS (
      INSERT INTO "User"
        (id, name, "telegramUserId", "telegramUsername",
         "telegramFirstName", "updatedAt")
      VALUES
        (${idHint}, ${firstName}, ${tid}::bigint, ${username},
         ${firstName}, NOW())
      ON CONFLICT ("telegramUserId") DO UPDATE SET
        "telegramUsername" = EXCLUDED."telegramUsername",
        "telegramFirstName" = EXCLUDED."telegramFirstName",
        "updatedAt" = NOW()
      RETURNING id, name, "telegramUserId", "telegramUsername",
                "telegramFirstName"
    )
    SELECT * FROM ins
  `;
  return rows[0];
}
